#!/bin/bash
#
# Provision for development on local/vagrant system
#
# Copy bin_provision_template to bin/provision in your application root directory
# for configuring your local/vagrant development system
# (Review provision.sh first, to confirm you agree with the choices I have made)

url=https://gist.githubusercontent.com/ianheggie/978f54360dd00f8e8f2494c229f63459/raw/provision.sh
tmp=/tmp/provision.$$
trap "rm -f $tmp" 0
if wget $url -O $tmp || curl $url -o $tmp
then
  bash $tmp "$@"  # adjust to add project specific arguments
fi
rm -f $tmp
