#!/bin/bash
#
# Provision for development on local/vagrant system
#
# Copy bin_provision_template to bin/provision in your application root directory
# for configuring your local/vagrant development system
#
# (Review provision.sh first, to confirm you agree with the choices I have made)

url=https://raw.githubusercontent.com/ianheggie/provision_vagrant/master/provision.sh
mkdir -p $HOME/bin
latest_script=$HOME/bin/provision.sh
tmp=/tmp/$$.sh
rm -f $tmp
if curl $url -o $tmp || wget $url --unlink -O $tmp
then
  trap "rm -f $tmp" 0
  rm -f $latest_script
  echo Copying $tmp to $latest_script
  cp -f $tmp $latest_script
  echo Running $tmp "$@"
  bash $tmp "$@"  # adjust to add project specific arguments using set -- arg1 arg2 arg3... or vagrant shell provisioner args
fi
rm -f $tmp
